### PR TITLE
[draytonwiser] fix represenation property

### PR DESCRIPTION
**Pull request by Hilbrand**
- Added missing representation property to thing xml file
- Changed representation property of bridge to network address because serialnumber is not know at discovery time.
- Added id as representation property to controller. To find only 1 controller if the user uses a  different thinguid as the discovery.
- Fixed hot water thing discovery. It doesn't have a serial number and also no related to a device.
- Improved the readme formatting.
- And some other review comments.

### CODE REVIEW

**Comment by andrew-schofield** [comment]
I'm just checking that these changes work properly when I install it locally

**Review by andrew-schofield — CHANGES_REQUESTED** [review]
Sadly it appears something has broken with the way handlers are being registered?

When I run an autodiscovery, it finds the heathub, but when I try and add it in PaperUI I get an error 500 and the following in the log:

```
2020-08-04 20:58:58.665 [ERROR] [st.core.internal.thing.ThingResource] - Exception during HTTP PUT request for update config at 'things/draytonwiser:heathub:WiserHeat0274E1/config'

java.lang.IllegalStateException: Thing with UID draytonwiser:heathub:WiserHeat0274E1 has no handler attached.
```

I'm not really sure what has caused this to break

**Comment by Hilbrand** [comment]
This can be an anomaly when a binding is updated and things with the previous version were created. In such case you need to clean the cache. See if this fixes the issue.

**Comment by andrew-schofield** [comment]
Ok, I'll have another go later.
I thought I'd been careful to remove all my existing things, but maybe not.

**Comment by andrew-schofield** [comment]
I've tried this on a fresh openhab installation, and it appears to work fine. I must say I'm not a particular fan of using serial numbers as representation properties as it makes simple-linked items very difficult to decipher, i.e. all my TRV items can now only be identified by serial number.

**Review by andrew-schofield — APPROVED** [review]

**Pull request merged**
